FROM python:3.12-slim

# System dependencies needed for PyAudio + FFmpeg
RUN apt-get update && apt-get install -y \
    portaudio19-dev \
    curl wget nano g++ gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install WhisperLive from GitHub
RUN pip install whisper-live

VOLUME ["/app"]

EXPOSE 8501

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]